language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: rk1GbuXfnpbk3flZB9IZi2GblVtRET+lDaGLHcouv0X+8MZM385p16ru128T0y4d/xOfcIR//BOSr3/gqhT18FWmzMrXRzre8kG9KJt9ISBF7htxgh0tDiI6pUvJEHKc2fdbKElSmTzAkaNNiEly5B/KYHZmMIi+BxbB6xVPi0XyaRrJuHdpEduK0Fw2bocP1RAlNiYCuE/zv13b7qXnQL5IPpalhuRS6lw38Yv3SuDjFcYxk2hCPAw8yqXiD6ZFLd9TMcFCNG0V7twrW78EAd/ZbLRxKFXyDJxPWKoCniYhGJxmfEIyJRfMgrhgo9pxAC7M1Wthp3qBi3submpw4POKPbMQYSbdISDeZXlsyNIOUvcNSl6va0nIhbttXUyED2mHezssy11pupuPrssVpL6CnzKzmBQF7mlLRxEJMVXFTApboEhRlfwqYJI+1DvZdUmXGvA9i9k0kUtflJgmms7vBCm7IDlJrmXORmH3JuYABLGf2I+ZunGLDVsE2u+PeCkAOkq+4oVBwbLO629Rwtg2tBeeYSxAzc3xCQpILXWJqXBqy+dQV3YqnD/tPv7HC73xfHs+tB/8yNscAL2FpY3ZnnXT9UsteHT80u3PyVsjnoX0dWt+EnP/tt+FsL0P5IgWUgJR6sjxz1Z4fPO9r/E79nbQs/9SiStXPI0UgjY=
  app: trekintrails
  skip_cleanup: true
  on:
    repo: angemiklos/trek-in-trails
